### PR TITLE
ci: use `pre-commit` also locally

### PR DESCRIPTION
**Pull request by Borda**
Checklist before merging this PR:
- [x] Mentioned all issues that this PR fixes or addresses.
- [x] Summarized the updates of this PR under **Summary**.
- [x] Added an entry under **Unreleased** in the [Changelog](../CHANGELOG.md). 

Addresses https://github.com/unit8co/darts/pull/2323#discussion_r1565293055

### Summary

use pre-commit also locally instead of calling separate tools

### CODE REVIEW

**Review by madtoinou — APPROVED** [review]
Thanks @Borda for creating a separate PR for this, using pre-commit as a command for linting/formatting looks very neat.

**Comment by Borda** [comment]
> Could you add an entry to `CHANGELOG.md` under [this section](https://github.com/unit8co/darts/blob/master/CHANGELOG.md?rgh-link-date=2024-04-15T12%3A48%3A39Z#for-developers-of-the-library) (for the other PRs as well)?

added [53256bc](https://github.com/unit8co/darts/pull/2327/commits/53256bc2bc144535fb3bd4fe1bb0d874d4a84fe8)

**Comment by dennisbader** [comment]
Hi @Borda, there are merge conflicts from the `CHANGELOG.md`. I could fix these myself for all the PRs however, it seems I don't have write permission to the forked repo. 
Would it be possible to grant me access (I'd also like to slightly adapt the content for the changes in CHANGELOG)? 
If not, you can also fix the conflicts, we merge all PRs and I'll update the content later.

**Comment by Borda** [comment]
> Would it be possible to grant me access (I'd also like to slightly adapt the content for the changes in CHANGELOG)?

I di not do any restrictions, so all maintainers shall be able to push

**Comment by dennisbader** [comment]
@Borda, the other PR was merged. If you merge the master into this one and move the changelog entry to the unreleased section, we're good to go.

**Comment by Borda** [comment]
@dennisbader ready

**Pull request merged**
