### PR TITLE
Fix/isort and pyupgrade issues

### PR DESCRIPTION
**Pull request by gdevos010**
This is done as a separate PR so that the resulting squash-merge commit can be added to the .git-blame-ignore-revs file in the #747 PR

### CODE REVIEW

**Comment by tomasvanpottelbergh** [comment]
Hey @gdevos010, thanks for this! Could you remove any of the configuration or changes to `.git-blame-ignore-revs` from this PR? It's best if this PR is purely applying the changes, then we can ignore it in #747 once this one is merged.

**Comment by gdevos010** [comment]
not sure why it was closed

**Review by tomasvanpottelbergh — APPROVED** [review]
Happy to merge this now. WDYT @hrzn?

**Comment by hrzn** [comment]
> Happy to merge this now. WDYT @hrzn?

👍

**Pull request merged**
