### PR TITLE
Adding comet.ml 

### PR DESCRIPTION
**Pull request by gitbooo**
Fixes #.

### Summary

Instead of Tensorboard, you can track your experiences using comet.ml:

### Other Information
https://www.comet.ml/site/
https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.loggers.comet.html

### CODE REVIEW

**Review by dennisbader — COMMENTED** [review]
Hi @gitbooo and thanks for the initiative.

You should already be able to use this by adding the logger to your `pl_trainer_kwargs`:

```
pl_trainer_kwargs = {
    ..., 
    "logger": pl_loggers.CometLogger(api_key=api_key, workspace="", project_name="logs"),
}
model = NBEATSModel(..., pl_trainer_kwargs=pl_trainer_kwargs)
```
Checkout [PyTorch Lightning's Trainer](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#trainer-class-api) for more information.

**Comment by hrzn** [comment]
@gitbooo in view of @dennisbader 's comment, could you maybe turn this PR into a documentation improvement? You could extend the docstring of Torch Models to explain how logging can be done with different backends using `pl_trainer_kwargs`. I think this would be a better option than inflating the API of torch models (to accept e.g. API key as a new argument).

**Comment by hrzn** [comment]
@gitbooo are you still willing to finish off this PR by extending the docstrings?

**Comment by hrzn** [comment]
> > @gitbooo are you still willing to finish off this PR by extending the docstrings?
> 
> Sorry for being late, I will love to prepare the previously said docstring, and I agree that this approach is better than committing into the code

Hi @gitbooo I'll close off this PR for now, feel free to open a new one with the docstring updated. Thanks!

**Pull request closed without merging**
