### PR TITLE
[WIP] fix/conda-recipe: Fix building from meta.yaml

### PR DESCRIPTION
**Pull request by xfiderek**
Fixes #.
* Conda recipe not working

### Summary
I've managed to create conda environment with darts built from conda recipe. To make it work `torch` had to be replaced with `pytorch` in meta.yaml (discrepancy between pypi and anaconda).

Steps to build
* go to root directory of package
* `conda build -c conda-forge -c pytorch conda_recipe/darts/`
* Create new environment with  `conda create -n ${ENV_NAME} darts`

Currently `test_models_denoising (darts.tests.test_regression_models.RegressionModelsTestCase)` is failing for both python 3.8.10 and 3.7 with following traceback
```python
======================================================================
ERROR: test_models_denoising (darts.tests.test_regression_models.RegressionModelsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/blazejfiderek/GitHub/darts/darts/tests/test_regression_models.py", line 179, in test_models_denoising
    self.helper_test_models_accuracy(self.ts_sum1, self.ts_exog1, 1.5)
  File "/Users/blazejfiderek/GitHub/darts/darts/tests/test_regression_models.py", line 168, in helper_test_models_accuracy
    prediction = model_instance.predict(n=len(test_f), exog=test_f)
  File "/Users/blazejfiderek/GitHub/darts/darts/models/regression_model.py", line 286, in predict
    forecast = self.model.predict(forecasting_data, **kwargs)
  File "/Users/blazejfiderek/anaconda3/anaconda3/envs/dartseight/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 238, in predict
    return self._decision_function(X)
  File "/Users/blazejfiderek/anaconda3/anaconda3/envs/dartseight/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 220, in _decision_function
    X = check_array(X, accept_sparse=['csr', 'csc', 'coo'])
  File "/Users/blazejfiderek/anaconda3/anaconda3/envs/dartseight/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/Users/blazejfiderek/anaconda3/anaconda3/envs/dartseight/lib/python3.8/site-packages/sklearn/utils/validation.py", line 720, in check_array
    _assert_all_finite(array,
  File "/Users/blazejfiderek/anaconda3/anaconda3/envs/dartseight/lib/python3.8/site-packages/sklearn/utils/validation.py", line 103, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

----------------------------------------------------------------------
```

**But this test fails also for the classic installation via pip on my laptop**. It would be nice if someone checked it on another machine. That is mostly the reason why i made this PR public in WIP state.

### Other Information

* Conda builds the package with python 3.8.10 by default , but tested it also with specifying `python=3.7` in `conda create` command and it works as well (except for one test failing)

### TODO in this PR
* Run unittests on conda build (can be declared in meta.yaml)
* Add guidelines to the README

### Next steps (out of scope of this PR)
* add conda build to the CI to check if tests are passing
* create conda channel for unit8 to make possible to do `conda install -c unit8 darts`

### CODE REVIEW

**Review by hrzn — COMMENTED** [review]
Thanks for the proposal @xfiderek !
In parallel we also have @tomasvanpottelbergh who is currently looking at this, I suggest we try to merge both of your efforts if possible.

**Comment by tomasvanpottelbergh** [comment]
Thanks! I tried building your branch, but it seems newer conda-build versions don't accept the requirements any more without a space in between the name and the version number. I also can't really tell why this test is failing.

I built on top of @hrzn's work [here](https://github.com/unit8co/darts/tree/feat/conda-package): The idea there is to put the requirements statically in meta.yaml, which I think is necessary for publishing on conda-forge. I guess this would not be necessary if we have our own channel, but this means we should handle more of the build process?

Could you check if you are able to build the [feat/conda-package](https://github.com/unit8co/darts/tree/feat/conda-package) branch? Input on best practices for conda-packages is more than welcome!

**Comment by xfiderek** [comment]
Hi @tomasvanpottelbergh . Could you tell me what version of conda and conda build are you using? I've updated conda right now and it still builds ok. Conda version: conda 4.10.3, conda-build version: conda-build 3.21.4

Regarding conda-forge - According to [this blogpost](https://levelup.gitconnected.com/publishing-your-python-package-on-conda-and-conda-forge-309a405740cf) all dependencies must come from conda-forge as well and we use pytorch channel in darts :/, so getting there might be hard.

**Comment by xfiderek** [comment]
And btw i will try your build tommorow, but if we could easily inject dependencies instead of specyfing them manually i think it would be nice, but I am open to discussion ofc :)

**Comment by tomasvanpottelbergh** [comment]
> Hi @tomasvanpottelbergh . Could you tell me what version of conda and conda build are you using? I've updated conda right now and it still builds ok. Conda version: conda 4.10.3, conda-build version: conda-build 3.21.4
I must have done something wrong, because now I can build your branch (same conda and conda-build versions), after including `pip` in the `host` section. The tests also run on my machine (MBP M1 in Terminal under Rosetta).

> Regarding conda-forge - According to [this blogpost](https://levelup.gitconnected.com/publishing-your-python-package-on-conda-and-conda-forge-309a405740cf) all dependencies must come from conda-forge as well and we use pytorch channel in darts :/, so getting there might be hard.
Since pytorch is also available in the conda-forge channel, I don't think that should be a problem.

> And btw i will try your build tommorow, but if we could easily inject dependencies instead of specyfing them manually i think it would be nice, but I am open to discussion ofc :)
This is done in our branch using the `render_meta_file.py` script, but that is indeed an extra step. If conda-forge accepts recipes with dynamically generated dependencies, we could indeed use your solution.

**Comment by tomasvanpottelbergh** [comment]
I have opened a PR to get u8darts on conda-forge: https://github.com/conda-forge/staged-recipes/pull/15737, but unfortunately the Jinja templating does not work there...

We could keep @xfiderek's method for people that would like to build a conda package locally (not sure if that is common). Otherwise I suggest we build on the feat/conda-package branch to get our conda-forge recipe assembled with the least effort. What do you think?

**Comment by hrzn** [comment]
> I have opened a PR to get u8darts on conda-forge: [conda-forge/staged-recipes#15737](https://github.com/conda-forge/staged-recipes/pull/15737), but unfortunately the Jinja templating does not work there...
> 
> We could keep @xfiderek's method for people that would like to build a conda package locally (not sure if that is common). Otherwise I suggest we build on the feat/conda-package branch to get our conda-forge recipe assembled with the least effort. What do you think?

Sounds reasonable.

**Comment by hrzn** [comment]
@xfiderek @tomasvanpottelbergh shall we still merge this?

**Comment by tomasvanpottelbergh** [comment]
We can merge it and keep it alongside the conda-forge recipe. I can add the features in TODO when I look at the conda-forge recipe generation, unless @xfiderek wants to continue working on it.

**Review by hrzn — APPROVED** [review]

**Comment by xfiderek** [comment]
Hi! If you still want to merge it then I am ok with that, although i think that conda-forge installation is sufficient and better :). Up to you @tomasvanpottelbergh  @hrzn

**Comment by hrzn** [comment]
@xfiderek Then I'd say let's close it and we'll re-open if/when needed.

**Pull request closed without merging**
