### PR TITLE
lint: default pre-commit hooks & fixing

### PR DESCRIPTION
**Pull request by Borda**
Checklist before merging this PR:
- [x] Mentioned all issues that this PR fixes or addresses.
- [x] Summarized the updates of this PR under **Summary**.
- [x] Added an entry under **Unreleased** in the [Changelog](../CHANGELOG.md). 

### Summary

While working on #2323, I noticed that some simpler formatting issues could be fixed by defaulting to pre-commit hooks.
Also, is it possible that installing this [bot](https://github.com/marketplace/pre-commit-ci) would do linting on each PR so this lint step could be removed from all pipelines?

### CODE REVIEW

**Review by dennisbader — COMMENTED** [review]
Thanks also for this neat PR @Borda 🚀 💯 

Could you add a point to the CHANGELOG.md, describing the changes?

Also good suggestion with the pre-commit ci bot. Might be worth adding.
I assume the ci section in the `.pre-commit-config.yaml` will only be effective after installing the bot?

**Review by dennisbader — APPROVED** [review]

**Comment by Borda** [comment]
It seems to fail now on upload, so how about making the upload "alow-to-fail"?

**Comment by dennisbader** [comment]
Hi @Borda, I cannot fix the changelog conflicts (see image below):

Usually I have permission to change it through GitHub, but not for your forked repo.

image

**Comment by Borda** [comment]
> Usually I have permission to change it through GitHub, but not for your forked repo.

I think I know what the issue is; it is GH policy. If I have it forked with the personal account, it would work as you expect, but it is under an org, so the privileges are different... Let me check if it can be changed...

**Comment by dennisbader** [comment]
@Borda, sounds good. These Changelog updates I usually apply just before merging, so it would make things a bit easier if I could do it.

Also, I'm just preparing the 0.29.0 release. Will merge your PRs after that, since it's only relevant for developers.

**Comment by Borda** [comment]
> Also, I'm just preparing the 0.29.0 release. Will merge your PRs after that, since it's only relevant for developers.

sure, I have updated the chlog entry so it will be in the new section :)

**Comment by dennisbader** [comment]
Okay, so the new version is released. If you merge the latest master, I can merge this PR

**Pull request merged**
