### PR TITLE
Feat/format isort, linting, and pyupgrade

### LINKED ISSUE #739: Extending pre-commit functionality and linting
**Is your feature request related to a current problem? Please describe.**
no

**Describe proposed solution**
including more git pre-commit hooks can increase code clarity and prevent bugs.

**Describe potential alternatives**
N/A

**Additional context**
- flake8 can enforce code formatting not automatically fixed by black
- the pre-commit-hook repo can fix many basic annoyance
- pyupgrade can update deprecated methods
- mypy is a static typing 
- isort  or reorder_python_imports improves imports

**example**
```
repos:
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        language_version: python3.7
        args: [--safe, "--line-length", "100"]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language_version: python3

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-builtin-literals
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: check-ast
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    -   id: pyupgrade
        args: ['--py37-plus']

-    repo: https://github.com/pre-commit/mirrors-mypy
     rev: v0.910-1
     hooks:
     -   id: mypy
         args: [--ignore-missing-imports]
         additional_dependencies: [types-PyYAML, types-requests, types-PyMySQL]


-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus]

#-   repo: https://github.com/pre-commit/mirrors-isort
#    rev: v5.9.3
#    hooks:
#    -   id: isort
#        args: [-e, "--profile", "black"]
```

I would be willing to work on it but want to know if it would be merged

### PR DESCRIPTION
**Pull request by gdevos010**
Fixes #739 

### Summary

Extending the pre-commit linting.  
- isort
- end-of-file-fixer
- trailing-whitespace
- check-added-large-files
- requirements-txt-fixer
- mixed-line-ending
- pyupgrade

each addition had its own commit to see what changed 

### TODO:
- [x] Add .git-blame-ignore-revs file for commit #765

### CODE REVIEW

**Comment by hrzn** [comment]
Hi @gdevos010 , thanks! 
We are willing to merge this, but could you fix the conflicts?

**Comment by gdevos010** [comment]
@hrzn @tomasvanpottelbergh I merged in the changes. I added a PR for `.git-blame-ignore-revs` but Im not sure I set it up right

**Comment by tomasvanpottelbergh** [comment]
Thanks! See my comment https://github.com/unit8co/darts/pull/765#issuecomment-1027700137. Could you also add checks to the CI workflows in this PR? Because if we don't enforce it, these issues will have to be fixed regularly in the codebase.

**Comment by gdevos010** [comment]
@tomasvanpottelbergh I've never setup a CL workflow in github before. Is it simply adding these lines to `develop.yml` and `merge.yml`
```
      - name: "3. Lint using isort"
        uses: PyCQA/isort@5
        with:
          isort-version: "5.10.1"
```

**Comment by tomasvanpottelbergh** [comment]
The easiest would be to find the corresponding Github Action, but we can also just run it using a script. If you remove any config changes from #765, we can merge that one and I can add the CI config to this PR.

**Comment by gdevos010** [comment]
@tomasvanpottelbergh #765 is now just the .git-blame-ignore-revs change

**Comment by tomasvanpottelbergh** [comment]
Sorry if I wasn't clear @gdevos010, but we need a PR where the only changes are applying isort etc to the codebase, without the pre-commit and git-blame configuration. Can you do that in #765 please?

**Comment by gdevos010** [comment]
not sure why it closed

**Comment by gdevos010** [comment]
@tomasvanpottelbergh I sure hope I got it right this time

**Comment by gdevos010** [comment]
@tomasvanpottelbergh I believe this one is also ready to be merged in

**Comment by tomasvanpottelbergh** [comment]
@gdevos010 thanks for this, but we had a few more fixes and decided not to add the whitespace fixing in the end. We will add most of it, but won't enforce pyupgrade. I will close this PR and will try to get #797 merged soon, which include CI/CD integration.

**Comment by gdevos010** [comment]
@tomasvanpottelbergh Could you share why you decided to skip fixing the whitespaces? Just curious

**Comment by tomasvanpottelbergh** [comment]
It changed the hashes of our datasets (although we should fix that in the long term), but mainly because it was a pure pre-commit hook which is unenforceable in the CI pipelines.

**Pull request closed without merging**
