### PR TITLE
Feature/pretty plots

### PR DESCRIPTION
**Pull request by LeoTafti**
### Summary

Changes plots' appearance to (kind of) conform to Unit8's graphic chart. I think it could be a nice touch before the next release.

Defined a matplotlib stylesheet. I'm having trouble making the call to apply the stylesheet (`plt.style.use('u8plots.mplstyle')`) work from both a stand-alone example (e.g. a `test.py` file out of the project) and the notebooks, due to some relative URL stuff. I wasn't sure where to put this call either. Had to put the stylesheet in two places to make it work, which isn't satisfactory. Would need a little help on that point.

Other than that, it should work as is. Run the notebooks (and in particular `darts-intro.ipynb`) to see the new plots.

### Other Information

[line-plot-prediction.pdf](https://github.com/unit8co/darts/files/5282999/line-plot-prediction.pdf)
[acf-plot.pdf](https://github.com/unit8co/darts/files/5283000/acf-plot.pdf)
[residuals_analysis.pdf](https://github.com/unit8co/darts/files/5283001/residuals_analysis.pdf)

### CODE REVIEW

**Review by hrzn — COMMENTED** [review]
It doesn't work (at least for me) when using outside of the `darts` folder. For instance
```
[julien@mbp ~/Downloads] $ python test.py
Traceback (most recent call last):
  File "/Users/julien/anaconda3/envs/darts/lib/python3.8/site-packages/matplotlib/style/core.py", line 114, in use
    rc = rc_params_from_file(style, use_default_template=False)
  File "/Users/julien/anaconda3/envs/darts/lib/python3.8/site-packages/matplotlib/__init__.py", line 984, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/Users/julien/anaconda3/envs/darts/lib/python3.8/site-packages/matplotlib/__init__.py", line 914, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/Users/julien/anaconda3/envs/darts/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/julien/anaconda3/envs/darts/lib/python3.8/site-packages/matplotlib/__init__.py", line 900, in _open_file_or_url
    with open(fname, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../darts/u8plots.mplstyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from darts.utils.timeseries_generation import sine_timeseries
  File "/Users/julien/unit8/darts/darts/__init__.py", line 31, in <module>
    plt.style.use('../darts/u8plots.mplstyle')
  File "/Users/julien/anaconda3/envs/darts/lib/python3.8/site-packages/matplotlib/style/core.py", line 117, in use
    raise IOError(
OSError: '../darts/u8plots.mplstyle' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles
```

I think another option could perhaps be to specify "dynamic rc settings" inside our `__init__.py` file (see here: https://matplotlib.org/tutorials/introductory/customizing.html).

**Comment by LeoTafti** [comment]
Mmmh yes I was having the same problem and somehow didn't think about this possibility. Should be an easy fix and work reliably from everywhere, I'll look into it. Thanks !

**Comment by pennfranc** [comment]
Cool idea, looks nice!

**Review by hrzn — APPROVED** [review]
👍

**Pull request merged**
