### PR TITLE
fixed change log

### PR DESCRIPTION
**Pull request by gdevos010**
I made a few mistakes in the changelog for those two PRs.

### CODE REVIEW

**Comment by gdevos010** [comment]
@hrzn it looks like the protobuf library version jumped from protobuf==3.20.1 to protobuf==4.21.0. The tensorboard version did not change, nor does this happen locally when I run all the tests. Im not sure the proper way to handle this.

**Comment by hrzn** [comment]
> @hrzn it looks like the protobuf library version jumped from protobuf==3.20.1 to protobuf==4.21.0. The tensorboard version did not change, nor does this happen locally when I run all the tests. Im not sure the proper way to handle this.

It seems to be due to a [fresh issue with protobuf and tensorflow](https://github.com/PyTorchLightning/pytorch-lightning/issues/13159) which are dependencies of pytorch lightning. I would wait a few more hours/days to see if the issue is corrected by the maintainers - in the worst case we'll maybe pin the version of protobuf.


On another front: what's actually the change in the PR? I see only a space removed in the CHANGELOG diff. Am I missing something?

**Comment by gdevos010** [comment]
I added the new datasets under 0.19 and forgot to add the glu variants. The space was to trigger the PR workflow again

**Comment by gdevos010** [comment]
protobuf==4.21.1 did not fix it.

**Review by hrzn — APPROVED** [review]

**Pull request merged**
