### PR TITLE
Imp/Add new model StatsForecastAutoTBATS

### LINKED ISSUE #2609: add AutoTBATS from nixtla
**Describe proposed solution**
Current implementation of TBATS is slow, so I would suggest to integrate AutoTBATS from nixtla
https://nixtlaverse.nixtla.io/statsforecast/src/core/models.html#autotbats-2

### PR DESCRIPTION
**Pull request by cnhwl**
Checklist before merging this PR:
- [x] Mentioned all issues that this PR fixes or addresses.
- [x] Summarized the updates of this PR under **Summary**.
- [x] Added an entry under **Unreleased** in the [Changelog](../CHANGELOG.md).

Fixes #2609.

### Summary

Add new model StatsForecastAutoTBATS from nixtla.

### CODE REVIEW

**Review by dennisbader — CHANGES_REQUESTED** [review]
Thanks a lot for this PR @cnhwl, it looks very good and is almost ready to be merged 🚀 

Before merging could you address the points from below?

- [x] add entry to `CHANGELOG.md`
- [ ] add model to the `README.md`
- [ ] add model to `darts/userguide/covariates.md` [in this table](https://unit8co.github.io/darts/userguide/covariates.html#global-forecasting-models-gfms)
- [ ] run probabilistic tests by adding the model to `darts/tests/models/forecasting/test_probabilistic_models.py`

**Comment by cnhwl** [comment]
Thank you very much for your code review and guidance! @dennisbader. I'll finish the points above soon. 🤝
By the way, I submitted PR #2544 three months ago and am waiting for code review. Is there a timeline for this?

**Comment by cnhwl** [comment]
Hi! @dennisbader I'm trying to add the models to `darts/tests/models/forecasting/test_probabilistic_models.py`, but I'm finding that the `random_state` parameter doesn't exist for `StatsForecastAutoTBATS`, which is preventing it from passing the `test_fit_predict_determinism`. I would be very grateful if you could give me some help with this!

**Comment by dennisbader** [comment]
> Thank you very much for your code review and guidance! @dennisbader. I'll finish the points above soon. 🤝 By the way, I submitted PR #2544 three months ago and am waiting for code review. Is there a timeline for this?

Hi @cnhwl, our capacity is currently a bit limited and we still need some time to get to. Sorry for that, but we will get there eventually!

**Comment by dennisbader** [comment]
> Hi! @dennisbader I'm trying to add the models to `darts/tests/models/forecasting/test_probabilistic_models.py`, but I'm finding that the `random_state` parameter doesn't exist for `StatsForecastAutoTBATS`, which is preventing it from passing the `test_fit_predict_determinism`. I would be very grateful if you could give me some help with this!

I see, that is true :) 

Actually, in my conformal prediction PR #2552, I introduce the @random_method that can be used by any model to control the randomness (see [here](https://github.com/unit8co/darts/blob/f28c2e18ad07790e221f169cab31468fff44da95/darts/utils/utils.py#L684)). This will allow you to control the sampling.

Once we merge the PR (I think by end of next week), we can add this to our StatsForecastModels as well. Is it okay for you to wait until then?

Otherwise, the PR looks great and is ready to be merged :) Thanks a lot for the great work @cnhwl 🚀

**Comment by cnhwl** [comment]
> > Hi! @dennisbader I'm trying to add the models to `darts/tests/models/forecasting/test_probabilistic_models.py`, but I'm finding that the `random_state` parameter doesn't exist for `StatsForecastAutoTBATS`, which is preventing it from passing the `test_fit_predict_determinism`. I would be very grateful if you could give me some help with this!
> 
> I see, that is true :)
> 
> Actually, in my conformal prediction PR #2552, I introduce the @random_method that can be used by any model to control the randomness (see [here](https://github.com/unit8co/darts/blob/f28c2e18ad07790e221f169cab31468fff44da95/darts/utils/utils.py#L684)). This will allow you to control the sampling.
> 
> Once we merge the PR (I think by end of next week), we can add this to our StatsForecastModels as well. Is it okay for you to wait until then?
> 
> Otherwise, the PR looks great and is ready to be merged :) Thanks a lot for the great work @cnhwl 🚀

Thanks again for your help! @dennisbader Of course! I am more than willing to wait for your PR #2552, so please let me know when that happens. 🤝

**Comment by dennisbader** [comment]
Hi @cnhwl, just wanted to let you know that PR #2552 (conformal prediction)  has been merged now :)

**Comment by cnhwl** [comment]
Hi @dennisbader, I've resolved the code conflict and am ready to merge anytime now! 🚀

**Review by dennisbader — APPROVED** [review]
Looks great now, thanks @cnhwl 🚀 

I can add probabilistic support with randomness handling later for all statsforecast models.

**Pull request merged**
