### PR TITLE
Allows Path objects as paths

### PR DESCRIPTION
**Pull request by felixdivo**
**NOTE:** I am aware that this is not finished yet.

Fixes no opened issue.

### Summary

Loading and saving a model should allow for [path objects](https://docs.python.org/3/library/pathlib.html) to be passed.

### CODE REVIEW

**Comment by felixdivo** [comment]
Is this feature desired by the darts team? If yes, I'll have a look at the other types of models and maybe add a test. Is there already a test case for loading/saving checkpoints?

**Comment by madtoinou** [comment]
Hi,

You can find tests to save/load in the `darts/darts/tests/models/forecasting/test_torch_forecasting_model.py` file.

**Comment by dennisbader** [comment]
Closing this one as #1754 is soon ready to get merged.

**Comment by felixdivo** [comment]
Sorry, I did not have the time to complete this. Thanks @sudrich for taking it over! 😃

**Pull request closed without merging**
