### PR TITLE
HNiTS rename to match model naming convection 

### LINKED ISSUE #947: [BUG] Consistent model naming
**Describe the bug**
NHiTS class should be renamed to NHiTSModel to match naming convention of all other models.

(https://github.com/unit8co/darts/blob/611e4119d4bdd7c42cd20847039fed5ee7b0ff67/darts/models/forecasting/nhits.py#L421-L434)

### PR DESCRIPTION
**Pull request by gdevos010**
Fixes #947.

### CODE REVIEW

**Review by dennisbader — APPROVED** [review]
Very nice, thanks a lot! 💯

**Review by hrzn — COMMENTED** [review]
It was actually intentional to not put the `Model` part (we also have other models without this - and when I added NHiTS I thought it is redundant, and somewhat came to regret that we have it on the other models). But if you think there are good reasons to have it, we could leave it I guess.
Was this motivated by any practical concern?

**Comment by gdevos010** [comment]
It's for consistency. When I first started using the model, the name threw me off. They should all have it or none of them

**Comment by hrzn** [comment]
> It's for consistency. When I first started using the model, the name threw me off. They should all have it or none of them

OK, I guess I agree.

**Review by hrzn — APPROVED** [review]

**Pull request merged**
